AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join [ -, [ !Ref ParamProjectName, url, !Ref ParamENV ] ]
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  URLCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/create
      Runtime: go1.x
      Tracing: Active
      Policies:
      - Version: '2012-10-17' # Allow write access to DynamoDB table
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable

  URLResolve:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/resolve
      Runtime: go1.x
      Tracing: Active
      Policies:
      - Version: '2012-10-17' # Allow read access to DynamoDB table
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable

Parameters:
  ParamProjectName:
    Type: String
  ParamProjectScope:
    Type: String
  ParamProjectID:
    Type: String
  ParamENV:
    Type: String

Outputs:
  URL:
    Description: URL for HTTPS Endpoint
    Value:
      Fn::Join:
        - ''
        - - https://
          - Ref: ServerlessRestApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/"
          - Ref: ServerlessRestApiProdStage
